### ISSUE TITLE
Cannot build on Eclipse 2018-09 (4.9.0) Java 1.8

### ISSUE THREAD

**Issue by keithgutfreund-elsevier** [alejandro-du/chat-server#6]
I downloaded zip and imported in Eclipse as a Maven project.  The MainView.java has four errors:
- Line 60, log cannot be resolved: log.error(exception)  
- Line 66, log cannot be resolved: log.error(exception)  
- Line 77, getFrom() and getText() are undefined for the type Message

**Comment by alejandro-du** [comment]
You need to configure Lombok. See https://projectlombok.org
